[secrets]
# Set a strong password for the main app
password = "your_secure_password_here"

# Set a different password for admin access (optional but recommended)
admin_password = "your_admin_password_here"

# Your OpenAI API key
openai_api_key = "your_openai_api_key_here"
